# Generated by Django 4.2.24 on 2025-09-06 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('insta', models.CharField(max_length=20)),
                ('idade', models.IntegerField(default=0)),
                ('curso', models.CharField(choices=[], max_length=50)),
                ('hobbies', models.TextField(max_length=300)),
                ('bio', models.TextField(max_length=500)),
                ('musica_fav', models.CharField(max_length=20)),
                ('cor_fundo', models.CharField(default='#fefefe', max_length=7)),
                ('cor_fundo_grad', models.CharField(default='#fefefe', max_length=7)),
                ('gradiente', models.BooleanField(default=False)),
                ('cor_destaque', models.CharField(default='#fefefe', max_length=7)),
                ('fonte', models.CharField(choices=[], max_length=50)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('curtidas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.card')),
            ],
        ),
    ]
