# Generated by Django 4.2.24 on 2025-09-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('periodo', models.CharField(choices=[('1°', '1° Ano'), ('2°', '2° Ano'), ('3°', '3° Ano'), ('4°', '4° Ano')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='fonte',
        ),
        migrations.AlterField(
            model_name='card',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.curso'),
        ),
    ]
