# Generated by Django 4.2.24 on 2025-10-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_curso_remove_card_fonte_alter_card_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cor_destaque',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cor_fundo_grad',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='periodo',
        ),
        migrations.AddField(
            model_name='card',
            name='cor_texto',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='card',
            name='periodo',
            field=models.CharField(blank=True, choices=[('1', '1° Ano'), ('2', '2° Ano'), ('3', '3° Ano'), ('4', '4° Ano'), ('5', 'Já Formado')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cor_fundo',
            field=models.CharField(default='#3f3f3f', max_length=7),
        ),
        migrations.AlterField(
            model_name='card',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.curso'),
        ),
        migrations.AlterField(
            model_name='card',
            name='curtidas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
