# Generated by Django 4.2.24 on 2025-10-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_card_cor_destaque_remove_card_cor_fundo_grad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='card',
            name='hobbies',
            field=models.ManyToManyField(to='blog.hobby'),
        ),
    ]
