# Generated by Django 4.2.25 on 2025-10-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_hobby_remove_card_hobbies_card_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='curtidas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
