# Generated by Django 4.2.25 on 2025-10-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_card_curtidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
