# Generated by Django 4.2.25 on 2025-10-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_card_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cor_destaque',
            field=models.CharField(default='#1E90FF', max_length=7),
        ),
    ]
