# Generated by Django 4.2.25 on 2025-10-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_card_cor_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.CharField(default='Anônimo', max_length=50),
        ),
    ]
