# Generated by Django 4.2.25 on 2025-10-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fonte',
            field=models.CharField(choices=[('1', 'Inter'), ('2', 'Oswald'), ('3', 'DM Serif Display'), ('4', 'Playwrite DE SAS'), ('5', 'Abel'), ('6', 'Dancing Script'), ('7', 'Shadows Into Light'), ('8', 'Poppins')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='bio',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='card',
            name='musica_fav',
            field=models.CharField(max_length=100),
        ),
    ]
