# Generated by Django 4.2.25 on 2025-10-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_card_fonte_alter_card_bio_alter_card_musica_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='musica_fav',
            new_name='musica_favorita',
        ),
        migrations.AlterField(
            model_name='card',
            name='fonte',
            field=models.CharField(choices=[('1', 'Inter'), ('2', 'Oswald'), ('3', 'DM Serif Display'), ('4', 'Playwrite DE SAS'), ('5', 'Abel'), ('8', 'Poppins')], default='1', max_length=1),
        ),
    ]
